version: "3.8"

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: taskdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - task-network

  backend:
    build: ./backend
    environment:
      DB_HOST: db
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: taskdb
    ports:
      - "5001:5000"
    depends_on:
      - db
    networks:
      - task-network

networks:
  task-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
